### ISSUE TITLE
meross MSG100 is currently not supportet - homebridge-meross v6.0.0-beta.4

### ISSUE THREAD

**Issue by app-ch** [donavanbecker/homebridge-meross#301] opened 2021-07-26 17:08 UTC
homebridge-meross v6.0.0-beta.4

in the log file of homebridge i received the following message:
[Garage] is currently not supported, do create a github issue https://git.io/JtfVC with info:
with info:
{
  uuid: '21031902xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  onlineStatus: 1,
  devName: 'Garage',
  devIconId: 'device039_un',
  bindTime: 1627297448,
  deviceType: 'MSG100',
  subType: 'us',
  channels: [Array],
  region: 'eu',
  fmwareVersion: '3.2.3',
  hdwareVersion: '3.5.0',
  userDevIcon: '',
  iconType: 1,
  skillNumber: '',
  cluster: 1,
  domain: 'mqtt-eu.meross.com',
  reservedDomain: 'mqtt-eu.meross.com'
}

[7/26/2021, 5:02:11 PM] [Meross] [Garage] failed to refresh status as Cannot read property 'payload' of undefined at deviceLocalGarage.requestDeviceUpdate (/homebridge/node_modules/homebridge-meross/lib/device/local/garage.js:244:47).

**Comment by bwp91** [comment] 2021-07-27 16:47
Closing this issue as duplicate of #302

**Closed as completed by bwp91** 2021-07-27 16:47 UTC
