### ISSUE TITLE
Need Support for MSG100 Garage Door Opener

### ISSUE THREAD

**Issue by admoseremic** [donavanbecker/homebridge-meross#303] opened 2021-07-15 05:06 UTC
**Is your feature request related to a problem? Please describe.**

I've tried to connect my Meross MSG100 garage door opener to Homebridge, but I can't seem to get it working with this plugin or with the other Homebridge plugins.

**Describe the solution you'd like**

Please add support for the MSG100 garage door opener.

**Describe alternatives you've considered**

I've tried the other "homebridge-meross" plugin, however it never seems to connect properly and always gives me "failed to refresh status" errors.

**Additional context**

This is the message I got from the Homebridge logs: [MerossCloud] Device Type: msg100, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC

**Comment by bwp91** [comment] 2021-07-27 06:58
Please try the latest beta of homebridge-meross plugin. If you’re still using homebridge-meross-cloud then you’ll need to switch over.

**Comment by bwp91** [comment] 2021-07-27 16:48
Closing this as duplicate of #302

**Closed as completed** 2021-07-27 16:48 UTC
