### ISSUE TITLE
Plugin don´t work -> Disabling Plugin / Neither of username and password nor user key has been configured

### ISSUE THREAD

**Issue by Hitmn1** [donavanbecker/homebridge-meross#517] opened 2023-04-20 13:11 UTC
### What issue do you have? Please be as thorough and explicit as possible.

No function of my Meross devices with Homebridge. In the Meross app all runs smoothly. User and PW checked.

Log:

[Meross] Plugin initialised. Setting up accessories....
[Meross] Disabling cloud client as invalid device list received
[Meross] ***** Disabling plugin. *****
[Meross] ***** Neither of username and password nor user key has been configured. *****
[homebridge-meross] Terminating child process...
[homebridge-meross] Child process ended

### Details of your setup.

* I use Homebridge UI-X
* Which version of Homebridge do you have? -> 1.6
* Which platform do you run Homebridge? -> Raspberry Pi - Node.js = 18.16.0
* Which version of this plugin (homebridge-meross) do you have? V9.0.3
* Has the issue started since upgrading from a previous version? no
* Which Meross devices do you have that are causing issues? msg100 and mss425f

```

```

**Comment by losehose** [comment] 2023-04-20 15:04
same problem here.
plugin shuts down and local devices can't be controlled either.
Tried to create a whole new meross account with no devices connected and got the same error. 

I use Homebridge UI-X
Which version of Homebridge do you have? -> 1.6.0
Which platform do you run Homebridge? -> Raspberry Pi - Node.js = 18.16.0
Which version of this plugin (homebridge-meross) do you have? V9.0.3
Has the issue started since upgrading from a previous version? no
Which Meross devices do you have that are causing issues? MSS110

**Comment by josemmc95** [comment] 2023-04-20 15:36
Same problem here

**Comment by lion33319** [comment] 2023-04-20 15:46
Also same problem here. Didn’t change a thing and it worked until today.

**Comment by ikorbln** [comment] 2023-04-20 15:50
same here

**Comment by Stonie70** [comment] 2023-04-20 16:24
Same Problem:
[Meross] Disabling cloud client as invalid device list received - {"apiStatus":0,"sysStatus":0,"info":"","timestamp":1682007763,"data":[{"uuid":"2102239765530190842448e1e94d49b6","onlineStatus":1,"devName":"Stecker Carport","devIconId":"device026_eu","bindTime":1638464615,"deviceType":"mss620r","subType":"eu","channels":[{},{"type":"Switch","devName":"Switch 1","devIconId":"device001"},{"type":"Switch","devName":"Switch 2","devIconId":"device001"}],"region":"eu","fmwareVersion":"4.1.34","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2102239765530190842448e1e94d49b6/1638466992671.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2103294328489851855348e1e96818ae","onlineStatus":1,"devName":"TV-Uhr","devIconId":"device001_eu","bindTime":1674380983,"deviceType":"mss110rtl","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.2.3","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2103294328489851855348e1e96818ae/1674381056278.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2103222585522790846848e1e9665348","onlineStatus":1,"devName":"Poolschacht","devIconId":"device026_eu","bindTime":1666884846,"deviceType":"mss620r","subType":"eu","channels":[{},{"type":"Switch","devName":"LED Beleuchtung","devIconId":"device001"},{"type":"Switch","devName":"Stecker Poolschacht 2","devIconId":"device001"}],"region":"eu","fmwareVersion":"4.1.34","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2103222585522790846848e1e9665348/1666886293393.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2109137548008451857048e1e976e7ef","onlineStatus":1,"devName":"Neontelefon","devIconId":"device001_eu","bindTime":1639578100,"deviceType":"mss110","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"7.3.13","hdwareVersion":"7.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2109137548008451857048e1e976e7ef/1642442074423.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2006289931259051851148e1e9219941","onlineStatus":1,"devName":"Wohnzimmer Fenster","devIconId":"device024","bindTime":1612784187,"deviceType":"mss210","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.2.9","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2006289931259051851148e1e9219941/1620232534668.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2211019611740651080548e1e9ae803f","onlineStatus":1,"devName":"Kinderzimmer PC Stecker","devIconId":"device001_eu","bindTime":1677596247,"deviceType":"mss110","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"7.3.13","hdwareVersion":"7.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2211019611740651080548e1e9ae803f/1677596482282.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2103295651109951855348e1e967d36c","onlineStatus":1,"devName":"Heimkino Strom","devIconId":"device001_eu","bindTime":1672312909,"deviceType":"mss110rtl","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.2.3","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2103295651109951855348e1e967d36c/1672342240276.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2103292573226651855348e1e96819c7","onlineStatus":1,"devName":"Wandleuchte Sideboard","devIconId":"device001_eu","bindTime":1639063675,"deviceType":"mss110rtl","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.2.3","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2103292573226651855348e1e96819c7/1642442010934.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2211017452825051080548e1e9ae8074","onlineStatus":1,"devName":"Stecker Arbeitszimmer","devIconId":"device001_eu","bindTime":1678902912,"deviceType":"mss110","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"7.3.13","hdwareVersion":"7.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2211017452825051080548e1e9ae8074/1679346811609.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2007082340759290818648e1e923873e","onlineStatus":1,"devName":"Poolpumpe","devIconId":"device026_eu","bindTime":1652868284,"deviceType":"mss620","subType":"eu","channels":[{},{"type":"Switch","devName":"Poolpumpe","devIconId":"device001"},{"type":"Switch","devName":"Stecker Terassen Esstisch","devIconId":"device001"}],"region":"eu","fmwareVersion":"4.1.32","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2007082340759290818648e1e923873e/1652883962477.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2007082689718590818648e1e9238d70","onlineStatus":1,"devName":"Stecker Terrasse","devIconId":"device026_eu","bindTime":1671465850,"deviceType":"mss620","subType":"eu","channels":[{},{"type":"Switch","devName":"Switch 1","devIconId":"device001"},{"type":"Switch","devName":"Switch 2","devIconId":"device001"}],"region":"eu","fmwareVersion":"4.1.32","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2007082689718590818648e1e9238d70/1671477959373.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2211014497500651080448e1e9ae2144","onlineStatus":1,"devName":"Dachstuhl","devIconId":"device001_eu","bindTime":1679133643,"deviceType":"mss110","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"7.3.13","hdwareVersion":"7.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2211014497500651080448e1e9ae2144/1679346939644.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2211015024348751080448e1e9ae0547","onlineStatus":1,"devName":"TV LED Stecker Daniel","devIconId":"device001_eu","bindTime":1679072400,"deviceType":"mss110","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"7.3.13","hdwareVersion":"7.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2211015024348751080448e1e9ae0547/1679346871281.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2103294511415551855348e1e9681af8","onlineStatus":1,"devName":"Wandbeleuchtung","devIconId":"device001_eu","bindTime":1639066227,"deviceType":"mss110rtl","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.2.3","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2103294511415551855348e1e9681af8/1642442042557.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2006285275084351851148e1e921dd25","onlineStatus":1,"devName":"Küche Fenster","devIconId":"device024","bindTime":1612785357,"deviceType":"mss210","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.2.9","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/872861/2006285275084351851148e1e921dd25/1620232620088.jpg","iconType":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","cluster":2,"hardwareCapabilities":[]}]} at default.getDevices (file:///usr/lib/node_modules/homebridge-meross/lib/connection/http.js:144:15).
[4/20/2023, 6:22:43 PM] [Meross] ***** Disabling plugin. *****
[4/20/2023, 6:22:43 PM] [Meross] ***** Neither of username and password nor user key has been configured. *****

**Comment by josemmc95** [comment] 2023-04-20 18:18
Fixed with latest update.

it was quick.

**Comment by ikorbln** [comment] 2023-04-20 18:39
confirmed, it worked again, thx. :-)

**Comment by losehose** [comment] 2023-04-20 19:22
can also confirm. Works again. Thank you :)

**Comment by Stonie70** [comment] 2023-04-20 19:24
It works again, thanks for this quick solution!

**Comment by Hitmn1** [comment] 2023-04-21 17:32
Thanks for the quick solution ...

**Comment by bwp91** [comment] 2023-04-21 18:30
Yep should be fixed in the new version of the plugin 👍🏻

**Closed as completed by bwp91** 2023-04-21 18:30 UTC
